import assert from 'node:assert/strict';
import test from 'node:test';
import worker from '../worker/index.js';
function fixture(){let serial=0;const map=new Map();const env={ADMIN_PASSWORD:'test-password-only-not-production',ADMIN_SESSION_SECRET:'test-signing-secret-only-not-production',LOGIN_LIMITER:{limit:async()=>({success:true})},FORM_LIMITER:{limit:async()=>({success:true})},BUCKET:{get:async k=>map.has(k)?{etag:map.get(k).etag,json:async()=>JSON.parse(map.get(k).body)}:null,put:async(k,body,opts={})=>{const old=map.get(k);if(opts.onlyIf?.etagDoesNotMatch==='*'&&old)return null;if(opts.onlyIf?.etagMatches!==undefined&&old?.etag!==opts.onlyIf.etagMatches)return null;const row={etag:'etag-'+(++serial),body};map.set(k,row);return row},list:async({prefix})=>({objects:[...map.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))})}};const req=(path,method='GET',body,headers={})=>new Request('https://ftr.example'+path,{method,headers:{Origin:'https://ftr.example',...headers,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const run=(...args)=>worker.fetch(req(...args),env);return {env,run};}
async function login(f){const r=await f.run('/api/auth/login','POST',{password:f.env.ADMIN_PASSWORD});assert.equal(r.status,200);assert.match(r.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Strict/);return r.headers.get('Set-Cookie').split(';')[0];}
test('public pages and brand assets load without ChatGPT identity',async()=>{const f=fixture();assert.equal((await f.run('/')).status,200);assert.equal((await f.run('/brand/mark.jpg')).headers.get('Content-Type'),'image/jpeg');assert.equal((await(await f.run('/api/auth/session')).json()).admin,false);});
test('admin API rejects anonymous and forged preview headers',async()=>{const f=fixture();const d=await(await f.run('/api/content')).json();assert.equal((await f.run('/api/content','PUT',d)).status,401);assert.equal((await f.run('/api/content','PUT',d,{'oai-authenticated-user-id':'spoofed'})).status,401);assert.equal((await f.run('/api/admin/records')).status,401);});
test('login rejects wrong password, cross-origin and throttled attempts',async()=>{const f=fixture();assert.equal((await f.run('/api/auth/login','POST',{password:'incorrect'})).status,401);assert.equal((await f.run('/api/auth/login','POST',{password:f.env.ADMIN_PASSWORD},{Origin:'https://evil.example'})).status,403);f.env.LOGIN_LIMITER.limit=async()=>({success:false});assert.equal((await f.run('/api/auth/login','POST',{password:f.env.ADMIN_PASSWORD})).status,429);});
test('unconfigured admin and form protections fail closed',async()=>{const f=fixture();delete f.env.ADMIN_PASSWORD;assert.equal((await f.run('/api/auth/login','POST',{password:'anything'})).status,503);delete f.env.FORM_LIMITER;assert.equal((await f.run('/api/newsletter','POST',{email:'person@example.com',consent:true})).status,503);});
test('signed admin session authorizes saves and detects concurrent conflicts',async()=>{const f=fixture(),Cookie=await login(f);const d=await(await f.run('/api/content')).json();assert.equal((await f.run('/api/content','PUT',d,{Cookie})).status,200);assert.equal((await f.run('/api/content','PUT',d,{Cookie})).status,409);assert.equal((await f.run('/api/content','PUT',d,{Cookie,Origin:'https://evil.example'})).status,403);assert.equal((await(await f.run('/api/auth/session','GET',null,{Cookie})).json()).admin,true);});
test('tampering and secret/password rotation invalidate sessions',async()=>{const f=fixture(),Cookie=await login(f);assert.equal((await f.run('/api/admin/records','GET',null,{Cookie:Cookie+'x'})).status,401);f.env.ADMIN_PASSWORD+='changed';assert.equal((await f.run('/api/admin/records','GET',null,{Cookie})).status,401);});
test('public forms validate consent and admin alone reads inbox',async()=>{const f=fixture();assert.equal((await f.run('/api/newsletter','POST',{email:'person@example.com',consent:false})).status,400);assert.equal((await f.run('/api/newsletter','POST',{email:'person@example.com',consent:true})).status,200);assert.equal((await f.run('/api/contact','POST',{name:'Test Person',email:'person@example.com',message:'An example message.'})).status,200);const Cookie=await login(f);const d=await(await f.run('/api/admin/records?type=messages','GET',null,{Cookie})).json();assert.equal(d.records.length,1);});
test('logout clears secure cookie and invalid uploads are blocked',async()=>{const f=fixture(),Cookie=await login(f);const out=await f.run('/api/auth/logout','POST',{}, {Cookie});assert.match(out.headers.get('Set-Cookie'),/Max-Age=0/);assert.equal((await f.run('/api/upload','POST',{}, {Cookie})).status,400);});
