const NOW=()=>Date.now();
const emailOK=s=>typeof s==='string'&&s.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
function str(v,max=5000){if(typeof v!=='string'||v.length>max)throw Error('Invalid entry');return v.trim();}
function fields(d){const out={};for(const k of ['name','display_name','address1','address2','city','region','postal','country'])out[k]=str(d[k]||'',k==='address1'||k==='address2'?200:100);if(!out.name||!out.address1||!out.city||!out.region||!out.postal)throw Error('Required profile fields missing');out.country=out.country||'US';out.display_name=out.display_name||out.name.split(' ')[0];return out;}
const publicMember=m=>m?{id:m.id,name:m.name,display_name:m.display_name,email:m.email,address1:m.address1,address2:m.address2,city:m.city,region:m.region,postal:m.postal,country:m.country,verified:!!m.verified}:null;
const rand=()=>b64url(crypto.getRandomValues(new Uint8Array(32)));
const hashToken=async t=>b64url(await digest(t));
async function passwordHash(password,salt,env){if(typeof env.MEMBER_PASSWORD_PEPPER!=='string'||env.MEMBER_PASSWORD_PEPPER.length<32)throw Error('Member password secret is not configured');const pepperKey=await crypto.subtle.importKey('raw',encoder.encode(env.MEMBER_PASSWORD_PEPPER),{name:'HMAC',hash:'SHA-256'},false,['sign']);const peppered=await crypto.subtle.sign('HMAC',pepperKey,encoder.encode(password));const k=await crypto.subtle.importKey('raw',peppered,'PBKDF2',false,['deriveBits']);const bytes=await crypto.subtle.deriveBits({name:'PBKDF2',salt:encoder.encode(salt),iterations:100000,hash:'SHA-256'},k,256);return b64url(new Uint8Array(bytes));}
const validPassword=s=>typeof s==='string'&&s.length>=12&&s.length<=256;
async function memberSession(r,env){if(!env.DB)return null;const c=(r.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('__Host-ftr_member='));if(!c)return null;const t=c.slice('__Host-ftr_member='.length);if(t.length>100)return null;return env.DB.prepare('SELECT m.* FROM members m JOIN member_sessions s ON s.member_id=m.id WHERE s.token_hash=? AND s.expires>?').bind(await hashToken(t),NOW()).first();}
function memberCookie(t,maxAge=604800){return '__Host-ftr_member='+t+'; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age='+maxAge;}
function emailConfigured(env){try{return !!env.RESEND_API_KEY&&!!env.EMAIL_FROM&&typeof env.MEMBER_PASSWORD_PEPPER==='string'&&env.MEMBER_PASSWORD_PEPPER.length>=32&&new URL(env.PUBLIC_SITE_URL).protocol==='https:';}catch{return false;}}
async function sendAccountMail(env,m,purpose){const token=rand(),h=await hashToken(token),exp=NOW()+(purpose==='reset'?3600000:86400000);await env.DB.prepare('INSERT INTO auth_tokens(token_hash,member_id,purpose,expires) VALUES(?,?,?,?)').bind(h,m.id,purpose,exp).run();const action=purpose==='reset'?'Reset your password':'Verify your email';const url=new URL(env.PUBLIC_SITE_URL).origin+'/#/account?'+purpose+'='+encodeURIComponent(token);try{const resp=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':'ftr-'+purpose+'-'+h},body:JSON.stringify({from:env.EMAIL_FROM,to:[m.email],subject:action+' — Finish The Race Motorsports',text:action+' for your FTR account:\n\n'+url+'\n\n'+(purpose==='reset'?'This link expires in one hour.':'This link expires in 24 hours.')+' If you did not request this, ignore this email.'})});if(!resp.ok)throw Error('Email delivery unavailable');}catch(e){await env.DB.prepare('DELETE FROM auth_tokens WHERE token_hash=?').bind(h).run();throw e;}}
// Automated screening is followed by human review. No community post is auto-published.
function offensive(text){const n=String(text).normalize('NFKD').replace(/[\u0300-\u036f\u200B-\u200F\u202A-\u202E\u2060-\u206F]/g,'').toLowerCase().replace(/[013457@$!]/g,c=>({'0':'o','1':'i','3':'e','4':'a','5':'s','7':'t','@':'a','$':'s','!':'i'}[c]));const clean=n.replace(/[^a-z\s]/g,' '),compact=n.replace(/[^a-z]/g,'');const strong=['fuck','motherfucker','cocksucker','nigger','nigga','faggot'];if(strong.some(w=>compact.includes(w)))return true;return /\b(shit|bullshit|bitch|bastard|asshole|dickhead|cunt)\b/.test(clean)||/\b(kill yourself|i will kill you|go kill yourself)\b/.test(clean);}
const hasPublicLink=s=>/(https?:\/\/|www\.|<\s*\/?\s*[a-z][^>]*>)/i.test(s);
const postSafe=p=>({id:p.id,type:p.type,author:p.author,title:p.title,body:p.body,image:p.type==='prayer'?'':p.image,video:p.type==='message'?p.video:'',audio:p.type==='message'?p.audio:'',link:p.type==='message'?p.link:'',created:p.created});
async function communityAPI(r,env,u){const p=u.pathname;if(!(p.startsWith('/api/members/')||p.startsWith('/api/fellowship/')||p.startsWith('/community-media/')))return null;if(!env.DB)return fail('Fellowship database is not connected yet. Follow FELLOWSHIP-SETUP.md.',503);
if(r.method!=='GET'&&!sameOrigin(r))return fail('Request origin not allowed.',403);
const isAdmin=await session(r,env);const member=await memberSession(r,env);
if(p.startsWith('/community-media/')&&r.method==='GET'){if(!/^\/community-media\/[a-f0-9-]+$/.test(p))return fail('Not found',404);const o=await env.BUCKET?.get(p.slice(1));if(!o)return fail('Not found',404);const published=await env.DB.prepare("SELECT id FROM fellowship_posts WHERE image=? AND status='published' AND visibility='public' LIMIT 1").bind(p).first();if(!published&&!isAdmin&&(!member||o.customMetadata?.memberId!==member.id))return fail('Not found',404);return new Response(o.body,{headers:{...SECURITY,'Content-Type':o.httpMetadata?.contentType||'image/jpeg','Cache-Control':'no-store'}});}
const json=()=>limitedJSON(r,22000);
const limit=async kind=>throttle(r,env,kind);
if(p==='/api/members/session'&&r.method==='GET')return response({member:publicMember(member),signupEnabled:emailConfigured(env)});
if(p==='/api/members/signup'&&r.method==='POST'){const denied=await limit('login');if(denied)return denied;if(!emailConfigured(env))return fail('Membership email service is not configured. Contact FTR or try again later.',503);const d=await json();if(!emailOK(d.email)||!validPassword(d.password)||d.consent!==true)return fail('Enter a valid email, a password of at least 12 characters, and accept the account terms.');const f=fields(d),email=d.email.toLowerCase().trim();const existing=await env.DB.prepare('SELECT * FROM members WHERE email=?').bind(email).first();if(existing){return response({ok:true,message:'If this address can be registered, verification instructions will be sent. Existing members can sign in or request a new verification email.'},202);}const id=crypto.randomUUID(),salt=rand(),pw=await passwordHash(d.password,salt,env);try{await env.DB.prepare('INSERT INTO members(id,email,name,display_name,address1,address2,city,region,postal,country,password_hash,password_salt,created) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,email,f.name,f.display_name,f.address1,f.address2,f.city,f.region,f.postal,f.country,pw,salt,new Date().toISOString()).run();}catch{return response({ok:true,message:'If this address can be registered, verification instructions will be sent.'},202);}try{await sendAccountMail(env,{id,email},'verify');}catch{return response({ok:true,message:'Your account was saved, but email delivery failed. Use “Resend verification” after the email service is restored.'},202);}return response({ok:true,message:'Check your inbox to verify your email, then sign in.'},201);}
if(p==='/api/members/verify'&&r.method==='POST'){const denied=await limit('login');if(denied)return denied;const d=await json(),token=str(d.token,100);const row=await env.DB.prepare("DELETE FROM auth_tokens WHERE token_hash=? AND purpose='verify' AND expires>? RETURNING member_id").bind(await hashToken(token),NOW()).first();if(!row)return fail('This verification link is invalid or expired. Request another email.');await env.DB.prepare('UPDATE members SET verified=1 WHERE id=?').bind(row.member_id).run();return response({ok:true});}
if((p==='/api/members/resend'||p==='/api/members/forgot')&&r.method==='POST'){const denied=await limit('login');if(denied)return denied;if(!emailConfigured(env))return fail('Email service is not configured.',503);const d=await json();if(!emailOK(d.email))return fail('Enter a valid email.');const m=await env.DB.prepare('SELECT * FROM members WHERE email=?').bind(d.email.toLowerCase().trim()).first();if(m&&(p.endsWith('forgot')||!m.verified)){try{await sendAccountMail(env,m,p.endsWith('forgot')?'reset':'verify');}catch{return fail('Email service is temporarily unavailable. Try again later.',503);}}return response({ok:true,message:'If an eligible account exists, an email has been sent.'});}
if(p==='/api/members/reset'&&r.method==='POST'){const denied=await limit('login');if(denied)return denied;const d=await json();if(!validPassword(d.password))return fail('Use a password of at least 12 characters.');const token=str(d.token,100),row=await env.DB.prepare("DELETE FROM auth_tokens WHERE token_hash=? AND purpose='reset' AND expires>? RETURNING member_id").bind(await hashToken(token),NOW()).first();if(!row)return fail('This reset link is invalid or expired.');const salt=rand(),pw=await passwordHash(d.password,salt,env);await env.DB.batch([env.DB.prepare('UPDATE members SET password_hash=?,password_salt=? WHERE id=?').bind(pw,salt,row.member_id),env.DB.prepare('DELETE FROM member_sessions WHERE member_id=?').bind(row.member_id),env.DB.prepare("DELETE FROM auth_tokens WHERE member_id=? AND purpose='reset'").bind(row.member_id)]);return response({ok:true});}
if(p==='/api/members/login'&&r.method==='POST'){if(typeof env.MEMBER_PASSWORD_PEPPER!=='string'||env.MEMBER_PASSWORD_PEPPER.length<32)return fail('Member password security is not configured.',503);const denied=await limit('login');if(denied)return denied;const d=await json();if(!emailOK(d.email)||typeof d.password!=='string'||d.password.length>256)return fail('Incorrect email or password.',401);const m=await env.DB.prepare('SELECT * FROM members WHERE email=?').bind(d.email.toLowerCase().trim()).first();const check=await passwordHash(d.password,m?.password_salt||'fixed-dummy-salt-for-timing',env);if(!m||!await equalPassword(check,m.password_hash))return fail('Incorrect email or password.',401);if(!m.verified)return fail('Verify your email before signing in. You can resend verification from the account page.',403);const token=rand();await env.DB.prepare('INSERT INTO member_sessions(token_hash,member_id,expires) VALUES(?,?,?)').bind(await hashToken(token),m.id,NOW()+604800000).run();return cookieResponse({member:publicMember(m)},memberCookie(token));}
if(p==='/api/members/logout'&&r.method==='POST'){const c=(r.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('__Host-ftr_member='));if(c)await env.DB.prepare('DELETE FROM member_sessions WHERE token_hash=?').bind(await hashToken(c.slice('__Host-ftr_member='.length))).run();return cookieResponse({ok:true},memberCookie('',0));}
if(p==='/api/members/profile'&&r.method==='PUT'){if(!member)return fail('Member sign-in required.',401);const f=fields(await json());await env.DB.prepare('UPDATE members SET name=?,display_name=?,address1=?,address2=?,city=?,region=?,postal=?,country=? WHERE id=?').bind(f.name,f.display_name,f.address1,f.address2,f.city,f.region,f.postal,f.country,member.id).run();return response({member:publicMember({...member,...f})});}
if(p==='/api/members/posts'&&r.method==='GET'){if(!member)return fail('Member sign-in required.',401);const result=await env.DB.prepare('SELECT id,type,title,body,status,visibility,created,moderation_note FROM fellowship_posts WHERE member_id=? ORDER BY created DESC LIMIT 100').bind(member.id).all();return response({posts:result.results});}
if(p==='/api/fellowship/feed'&&r.method==='GET'){const type=u.searchParams.get('type')||'message';if(!['message','testimony','prayer'].includes(type))return fail('Invalid feed.');const cursor=u.searchParams.get('cursor');let where="type=? AND status='published' AND visibility='public'";const args=[type];if(cursor){let c;try{c=JSON.parse(atob(cursor));}catch{return fail('Invalid page.');}if(typeof c.created!=='string'||typeof c.id!=='string')return fail('Invalid page.');where+=' AND (created<? OR (created=? AND id<?))';args.push(c.created,c.created,c.id);}const rows=(await env.DB.prepare('SELECT * FROM fellowship_posts WHERE '+where+' ORDER BY created DESC,id DESC LIMIT 13').bind(...args).all()).results;const more=rows.length>12,posts=rows.slice(0,12),last=posts.at(-1);return response({posts:posts.map(postSafe),nextCursor:more?btoa(JSON.stringify({created:last.created,id:last.id})):null});}
if(p==='/api/fellowship/upload-image'&&r.method==='POST'){if(!member?.verified)return fail('Verified member sign-in is required to upload a picture.',401);const denied=await limit('forms');if(denied)return denied;if(!env.BUCKET)return fail('Image storage is not configured.',503);const type=r.headers.get('Content-Type');if(!['image/jpeg','image/png','image/webp'].includes(type))return fail('Member posts support JPG, PNG, or WebP pictures only.',415);const max=10*1024*1024;if(Number(r.headers.get('Content-Length'))>max)return fail('Use a picture smaller than 10 MB.',413);const reader=r.body?.getReader();if(!reader)return fail('Choose a picture.');let length=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>max){await reader.cancel();return fail('Use a picture smaller than 10 MB.',413);}chunks.push(value);}const bytes=new Uint8Array(length);let off=0;for(const chunk of chunks){bytes.set(chunk,off);off+=chunk.length;}const jpg=length>3&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const png=length>8&&[137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v);const webp=length>12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!(type==='image/jpeg'&&jpg||type==='image/png'&&png||type==='image/webp'&&webp))return fail('This file does not appear to be a supported picture.',415);const key='community-media/'+crypto.randomUUID();await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:type},customMetadata:{memberId:member.id}});return response({url:'/'+key},201);}
if(p==='/api/fellowship/submit'&&r.method==='POST'){const denied=await limit('forms');if(denied)return denied;const d=await json();if(d.website)return response({ok:true,message:'Submission received.'});if(!['testimony','prayer'].includes(d.type))return fail('Invalid post type.');if(d.type==='testimony'&&(!member||!member.verified))return fail('Verified member sign-in is required for testimonies.',401);if(d.audio||d.video||d.link)return fail('Voice, video, and links are reserved for admin Messages from FTR. Member posts support pictures and text only.');if(d.type==='prayer'&&d.image)return fail('Prayer requests are text only.');const image=str(d.image||'',200);if(image){if(!/^\/community-media\/[a-f0-9-]+$/.test(image))return fail('Upload your picture using the member form.');const o=await env.BUCKET?.get(image.slice(1));if(!o||o.customMetadata?.memberId!==member?.id)return fail('You can only attach your own uploaded picture.',403);}const title=str(d.title,160),body=str(d.body||'',5000);if(!title||(!image&&body.length<10))return fail('Add a title and a picture or at least 10 characters of text.');if(offensive(title+' '+body))return fail('This submission contains language we cannot accept. Please revise it.',422);if(hasPublicLink(title+' '+body))return fail('Community submissions must be plain text without links or HTML.');if(d.email&&!emailOK(d.email))return fail('Enter a valid email or leave it blank.');const pub=d.type==='testimony'||d.share_public===true;if(pub&&d.consent_public!==true)return fail('Confirm permission to share this publicly after review.');const name=d.anonymous===true?'Anonymous':str(d.type==='testimony'?member.display_name:(d.author||(member?.display_name)||'Anonymous'),80)||'Anonymous';if(offensive(name))return fail('Please revise the display name.',422);const status=pub&&!image?'published':'pending';const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO fellowship_posts(id,type,member_id,author,email,title,body,image,visibility,consent_public,status,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,d.type,member?.id||null,name,d.email||member?.email||'',title,body,image,pub?'public':'private',pub?1:0,status,now,now).run();return response({ok:true,id,message:status==='published'?'Your post is now published.':pub?'Thank you. FTR will review your submission before it appears publicly.':'Your prayer request was sent privately to the FTR team.'},201);}
if(p.startsWith('/api/fellowship/admin/')){if(!isAdmin)return fail('Admin sign-in required.',401);
if(p==='/api/fellowship/admin/posts'&&r.method==='GET'){const type=u.searchParams.get('type')==='message'?'message':'community',status=u.searchParams.get('status')||'pending';let where=type==='message'?"type='message'":"type IN ('testimony','prayer')";const args=[];if(type!=='message'&&['pending','published','rejected','reviewed'].includes(status)){where+=' AND status=?';args.push(status);}const posts=(await env.DB.prepare('SELECT * FROM fellowship_posts WHERE '+where+' ORDER BY created DESC LIMIT 200').bind(...args).all()).results;return response({posts});}
if(p==='/api/fellowship/admin/members'&&r.method==='GET'){const members=(await env.DB.prepare('SELECT id,name,display_name,email,verified,created FROM members ORDER BY created DESC LIMIT 200').all()).results;return response({members});}
if(p==='/api/fellowship/admin/message'&&r.method==='POST'){const d=await json(),id=d.id?str(d.id,100):crypto.randomUUID(),title=str(d.title,160),body=str(d.body||'',10000);if(!title)return fail('Give your message a title.');const media={};for(const k of ['image','video','audio','link']){media[k]=str(d[k]||'',2000);if(!validURL(media[k]))return fail('Use HTTPS links or uploaded media.');}if(!body&&!Object.values(media).some(Boolean))return fail('Add text, media, or a link.');const now=new Date().toISOString(),status=d.publish===true?'published':'draft';if(d.publish===true&&offensive(title+' '+body))return fail('Please revise the language before publishing.',422);if(d.id){const old=await env.DB.prepare('SELECT type FROM fellowship_posts WHERE id=?').bind(id).first();if(!old||old.type!=='message')return fail('Message not found.',404);await env.DB.prepare('UPDATE fellowship_posts SET title=?,body=?,image=?,video=?,audio=?,link=?,status=?,updated=? WHERE id=?').bind(title,body,media.image,media.video,media.audio,media.link,status,now,id).run();}else await env.DB.prepare("INSERT INTO fellowship_posts(id,type,author,title,body,image,video,audio,link,visibility,consent_public,status,created,updated) VALUES(?,'message','FTR',?,?,?,?,?,?,'public',1,?,?,?)").bind(id,title,body,media.image,media.video,media.audio,media.link,status,now,now).run();return response({ok:true,id});}
if(p==='/api/fellowship/admin/moderate'&&r.method==='POST'){const d=await json(),id=str(d.id,100),action=d.action;if(!['approve','reject','unpublish','delete','resolve'].includes(action))return fail('Invalid moderation action.');const post=await env.DB.prepare('SELECT * FROM fellowship_posts WHERE id=?').bind(id).first();if(!post)return fail('Post not found.',404);if(action==='resolve'&&(post.type!=='prayer'||post.visibility!=='private'))return fail('Only private prayer requests can be marked reviewed.');if(action==='approve'&&offensive(post.title+' '+post.body+' '+post.author))return fail('This post contains blocked language.',422);if(action==='approve'&&post.type!=='message'&&(post.visibility!=='public'||!post.consent_public))return fail('This request is private. It cannot be published without the author’s permission.');const now=new Date().toISOString(),note=str(d.note||'',500);const mutation=action==='delete'?env.DB.prepare('DELETE FROM fellowship_posts WHERE id=?').bind(id):env.DB.prepare('UPDATE fellowship_posts SET status=?,moderation_note=?,updated=? WHERE id=?').bind(action==='approve'?'published':action==='reject'?'rejected':action==='resolve'?'reviewed':'pending',note,now,id);await env.DB.batch([mutation,env.DB.prepare('INSERT INTO moderation_log(id,post_id,action,created) VALUES(?,?,?,?)').bind(crypto.randomUUID(),id,action,now)]);return response({ok:true});}
}
return fail('Not found',404);}
